
spring:
  application:
    name: AddressService

  # Database
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ':::::::::::: Hikari DS Spades_1-MS POOL ::::::::::::'
      connection-timeout: 60000
      maximum-pool-size: 30
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://Address-postgres:5432/address_db
    username: postgres
    password: insy2s



  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql : true
    properties:
      hibernate:
        format_sql: true
#  Server configuration
eureka :
  instance:
    #hostname: AddressService
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://eureka-server:8761/eureka
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
user:
  url: http://GatewayService:8080/api/auth
message: From User Service 123
