spring:
  application:
    name: Client_Service

  security:
    user:
      name: mabrouka
      password: annabi
  datasource:
    url: jdbc:postgresql://Client-postgres:5432/client_db
    username: postgres
    password: insy2s
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
    
eureka :
  instance:
    hostname: Client_Service

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
      

server:
  port: 8081
user:
  url: http://GatewayService:8090/api/auth
