
spring:
  security:
    user:
      name: mabrouka
      password: annabi
  application:
      name: Email_Service

eureka :
  instance:
    preferIpAddress: true
    hostname: eureka-0
    #hostname: Email_Service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://eureka-server:8761/eureka
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka



#  Server configuration
server:
  port: 8086
user:
  url: http://GatewayService:8080/api/auth
