
spring:
  security:
    user:
      name: mabrouka
      password: annabi
  application:
      name: Email_Service

eureka :
  instance:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
     defaultZone: http://eureka-server:8761/eureka



#  Server configuration
server:
  port: 8086
user:
  url: http://GatewayService:8080/api/auth
