spring:
  application:
      name: Email_Service
eureka :
  instance:
  client:
    serviceUrl:
     defaultZone: http://eureka-server:8761/eureka



#  Server configuration
server:
  port: 8086
user:
  url: http://GatewayService:8080/api/auth
