eureka :
  instance:
   client:
    serviceUrl:
     defaultZone: http://GatewayService:8761/

 




spring:
  application:
    name: Gateway_Service
  security:
    user:
      name: mabrouka
      password: annabi
server:
  port: 8080





