spring:
  application:
    name: Gateway_Service
eureka :
  instance:
    #hostname: Gateway_Service
    preferIpAddress: true
    hostname: eureka-0
  client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
        #defaultZone: http://eureka-server:8761/eureka
        defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

security:
    user:
      name: mabrouka
      password: annabi


server:
  port: 8080





