spring:
  application:
    name: Gateway_Service
eureka :
  instance:
    hostname: Gateway_Service
  client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
        defaultZone: http://eureka-server:8761/eureka

security:
    user:
      name: mabrouka
      password: annabi


server:
  port: 8080





