spring:
  application:
    name: Ged_Service


    

  data:
    mongodb:
      database: admin
      username: insy2s
      password: insy2s
      host: Ged-mongodb
      port: 27017
server:
  port: 8088
#  Eureka configuration

eureka:
  instance:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

user:
  url: http://GatewayService:8080/api/auth

