spring:
  application:
    name: Ged_Service

  security:
    user:
      name: mabrouka
      password: annabi
    

  data:
    mongodb:
      database: admin
      username: insy2s
      password: insy2s
      host: Ged-mongodb
      port: 27017
server:
  port: 8088
#  Eureka configuration

eureka:
  instance:
      preferIpAddress: true
      hostname: eureka-0
    #  hostname: Ged_Service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://eureka-server:8761/eureka
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

user:
  url: http://GatewayService:8080/api/auth

