spring:
  application:
    name: PaySlip_Service
  security:
    user:
      name: insy2s
      password: insy2s


  # Database
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ':::::::::::: Hikari DS Spades_1-MS POOL ::::::::::::'
      connection-timeout: 60000
      maximum-pool-size: 30
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://Payslip-postgres:5432/payslip-db
    username: postgres
    password: insy2s

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql : true
    properties:
      hibernate:
        format_sql: true
#  Server configuration
server:
  port: 8087
  
  
eureka:
  instance:
    hostname: Payslip_Service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka


user:
  url: http://GatewayService:8090/api/auth

